# Generated by Django 3.2.18 on 2024-02-05 14:48

import commonsServer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0022_testcaseinsession_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCauseFromUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', commonsServer.models.TruncatingCharField(default='', max_length=150)),
                ('exception', models.CharField(default='', max_length=100)),
                ('errorMessage', models.CharField(default='.*', max_length=1000)),
                ('type', models.CharField(max_length=100)),
                ('testCase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declaredErrorCauses', to='snapshotServer.testcase')),
                ('testStep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declaredErrorCauses', to='snapshotServer.teststep')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorCauseDetected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('stepResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detectedErrorCauses', to='snapshotServer.stepresult')),
            ],
        ),
    ]
